version: '3'

services:
  database:
    image: 'postgres:latest'
    container_name: ${ENV}_${CONTAINER_NAME}
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - psql:/var/lib/postgresql/data/

volumes:
  psql: